export enum Icons {
  FAVICO = '/favico.ico',
  MEMBER = '/img/icons/member/member.png',
  TRAINER = '/img/icons/trainer/trainer.png',
  ADMIN = '/img/icons/admin/admin.png',
  TOAST_BLUE = '/img/icons/toast/Blue.png',
  TOAST_GREEN = '/img/icons/toast/Green.png',
  TOAST_RED = '/img/icons/toast/Red.png',
  TOAST_ORANGE = '/img/icons/toast/Orange.png',
  DOWNLOAD = '/img/icons/download.png',
  EYE = '/img/icons/eye.png',
  PDF = '/img/icons/pdf.png',
  HAMBURGER = '/img/icons/hamburger.png',
  ARROW_DOWN = '/img/icons/arrow-down.png',
  // Equipment
  DUMBBELL_5LB = '/img/icons/equipment/dumbbell/dumbell-5lb.png',
  DUMBBELL_10LB = '/img/icons/equipment/dumbbell/dumbell-10lb.png',
  DUMBBELL_15LB = '/img/icons/equipment/dumbbell/dumbell-15lb.png',
  DUMBBELL_20LB = '/img/icons/equipment/dumbbell/dumbell-20lb.png',
  DUMBBELL_25LB = '/img/icons/equipment/dumbbell/dumbell-25lb.png',
  DUMBBELL_30LB = '/img/icons/equipment/dumbbell/dumbell-30lb.png',
  DUMBBELL_35LB = '/img/icons/equipment/dumbbell/dumbell-35lb.png',
  DUMBBELL_40LB = '/img/icons/equipment/dumbbell/dumbell-40lb.png',
  DUMBBELL_45LB = '/img/icons/equipment/dumbbell/dumbell-45lb.png',
  DUMBBELL_50LB = '/img/icons/equipment/dumbbell/dumbell-50lb.png',
  DUMBBELL_55LB = '/img/icons/equipment/dumbbell/dumbell-55lb.png',
  DUMBBELL_60LB = '/img/icons/equipment/dumbbell/dumbell-60lb.png',
  DUMBBELL_65LB = '/img/icons/equipment/dumbbell/dumbell-65lb.png',
  DUMBBELL_70LB = '/img/icons/equipment/dumbbell/dumbell-70lb.png',
  DUMBBELL_75LB = '/img/icons/equipment/dumbbell/dumbell-75lb.png',
  DUMBBELL_80LB = '/img/icons/equipment/dumbbell/dumbell-80lb.png',
  DUMBBELL_85LB = '/img/icons/equipment/dumbbell/dumbell-85lb.png',
  DUMBBELL_90LB = '/img/icons/equipment/dumbbell/dumbell-90lb.png',
  DUMBBELL_95LB = '/img/icons/equipment/dumbbell/dumbell-95lb.png',
  DUMBBELL_100LB = '/img/icons/equipment/dumbbell/dumbell-100lb.png',
}